[package]
name = "tunnel-sketch-rs"
version = "0.1.0"
authors = ["Renan de Souza <haroflow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.11"
